### ISSUE TITLE
I get an error that QuickJS can't load the library

### ISSUE THREAD

**Issue by RGFTheCoder** [sntg-p/QuickJS-raylib#2]
`ReferenceError: could not load module filename 'lib/qjs-raylib/native/qjs-raylib.so' as shared library`

**Comment by RGFTheCoder** [comment]
For now I was able to solve this by building version 2.5.0 in static mode and adding the `-fPIC` flag in line 260 of the make file. You should state what version and type of library I should install

**Comment by sntg-p** [comment]
Just for the record, the Requirements section in the README.md has a link to the 2.5.0 binaries. I didn't have to build raylib from source to compile this project.
