### ISSUE TITLE
Compiling on windows?

### ISSUE THREAD

**Issue by joao678** [sntg-p/QuickJS-raylib#4]
Is there any way to compile this on windows? What tools are needed?

**Comment by sntg-p** [comment]
Sorry, I haven't tested it on Windows. You could use the provided Makefile as a guide. To compile the library you will probably need MinGW (you already have it if you used the raylib installer).

Feel free to comment if you try it!

**Comment by joao678** [comment]
I don't have that much experience with C/C++ but it seems that QuickJS itself dosen't have shared library modules support on windows, so there is no way of this working anyways
